"""Terminal renderer for `exadoctor scan` (roadmap Milestone 15).

Findings are grouped by status. PASS findings are collapsed to a one-line
summary (good news doesn't need detail); everything else -- CRITICAL,
WARNING, INFO, NOT_EVALUATED -- is shown in full, including its evidence,
limitations, and which capability it depended on, so missing evidence is
never silently invisible.
"""

from __future__ import annotations

from exadoctor.capabilities.report import build_report
from exadoctor.models.finding import Finding, FindingStatus
from exadoctor.models.snapshot import Snapshot

_STATUS_ORDER = [
    FindingStatus.CRITICAL,
    FindingStatus.WARNING,
    FindingStatus.INFO,
    FindingStatus.NOT_EVALUATED,
    FindingStatus.NOT_APPLICABLE,
]


def render_finding_lines(finding: Finding, show_drill_down: bool = True) -> list[str]:
    """Public: reused by other report renderers (e.g. the query analyzer's
    text report) so finding formatting stays identical everywhere.

    `show_drill_down=False` for the `exadoctor query` report specifically:
    every finding there is already about the one session/statement named
    in that report's own header, so repeating "exadoctor query <same ids>"
    on every evidence line would just be a self-referential echo, not a
    useful pointer to somewhere new (see `render_scan_text`, the only
    other caller, which leaves this on).
    """
    lines = [f"[{finding.status.value}] {finding.id} - {finding.title}", f"    {finding.summary}"]
    if finding.recommendation:
        lines.append(f"    recommendation: {finding.recommendation}")
    for evidence in finding.evidence:
        ts = f" at {evidence.timestamp.isoformat()}" if evidence.timestamp else ""
        unit = f" {evidence.unit}" if evidence.unit else ""
        # session_id/stmt_id are recorded on evidence (e.g. SQL-SLOW-001,
        # SQL-TEMP-001) precisely to identify the offending statement, but
        # were never surfaced in the text report -- a user had no way to
        # get from "here's a slow statement" to `exadoctor query`'s
        # required SESSION_ID/STMT_ID arguments without switching to
        # `--format json` and reading raw evidence fields by hand. Only
        # shown when both are present, since `query` requires both (a
        # session-only id, e.g. SESSION-LONG-001, isn't drillable this way).
        drill_down = (
            f" (drill in: exadoctor query {evidence.session_id} {evidence.stmt_id})"
            if show_drill_down and evidence.session_id is not None and evidence.stmt_id is not None
            else ""
        )
        lines.append(f"    evidence: {evidence.metric}={evidence.value}{unit}{ts} [{evidence.source}]{drill_down}")
    for limitation in finding.limitations:
        lines.append(f"    limitation: {limitation}")
    return lines


def render_findings_block(findings: list[Finding], show_drill_down: bool = True) -> list[str]:
    """Public: the "FINDINGS (...)" section (count summary, collapsed PASS
    list, full detail for everything else) shared by any text report that
    shows a list of Findings. `show_drill_down` is forwarded to
    `render_finding_lines` -- see its docstring."""
    lines: list[str] = []
    counts = {status: 0 for status in FindingStatus}
    for finding in findings:
        counts[finding.status] += 1
    summary = ", ".join(f"{count} {status.value}" for status, count in counts.items() if count)
    lines.append(f"FINDINGS ({len(findings)} total: {summary or 'none'})")
    lines.append("")

    passing = [f for f in findings if f.status == FindingStatus.PASS]
    if passing:
        lines.append(f"PASS ({len(passing)}): " + ", ".join(f.id for f in passing))
        lines.append("")

    for status in _STATUS_ORDER:
        for finding in findings:
            if finding.status == status:
                lines.extend(render_finding_lines(finding, show_drill_down=show_drill_down))
                lines.append("")

    return lines


def render_ai_explanation_block(ai_explanation: str | None) -> list[str]:
    """Public: shared "AI EXPLANATION" section for any text report --
    clearly labeled and separated from deterministic findings (roadmap
    requirement), with an explicit disclaimer restating what the AI layer
    may and may not do."""
    if not ai_explanation:
        return []
    return [
        "AI EXPLANATION (unverified -- generated by a local LLM, not part of the findings above)",
        "This may summarize/prioritize findings and explain terminology, but cannot change severity",
        "or introduce new evidence, and may be wrong. Always defer to the findings above for facts.",
        "",
        ai_explanation,
        "",
    ]


def render_scan_text(snapshot: Snapshot, ai_explanation: str | None = None) -> str:
    lines = ["EXADOCTOR SCAN REPORT", ""]
    lines.append(f"Database: {snapshot.database.version or 'unknown'} @ {snapshot.database.host}:{snapshot.database.port}")
    lines.append(f"Collected: {snapshot.collection_time.isoformat()}")
    if snapshot.database_time:
        lines.append(f"Database time: {snapshot.database_time.isoformat()}")
    lines.append("")

    capability_report = build_report(snapshot.database.version, snapshot.capabilities)
    lines.append(capability_report.render_text())
    lines.append("")

    lines.extend(render_findings_block(snapshot.findings))
    lines.extend(render_ai_explanation_block(ai_explanation))

    return "\n".join(lines).rstrip() + "\n"
